[package]
name = "sanzu-common"
version = "0.1.0"
authors = ["Fabrice Desclaux <fabrice.desclaux@cea.fr>"]
edition = "2018"
description = "Sanzu helper code"

[build-dependencies]
bindgen = "0.60.0"
prost-build = "0.10.4"

[dependencies]
anyhow = "1.0.53"
byteorder = "1.4.2"
env_logger = "0.9.0"
log = "0.4.13"
prost = "0.11.7"
rustls = "0.20.6"
rustls-pemfile = "1.0.0"
webpki-roots = "0.22"
x509-parser = "0.14.0"

[features]
kerberos = ["libgssapi"]
default = []

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9" }


[target.'cfg(unix)'.dependencies]
libgssapi = {version = "0.6.2", optional = true}
pam = {git = "https://github.com/1wilkens/pam.git", rev="1c38df0660ade4f6db878a0ed6952c05d88f721f"}
